config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener_web" if Rails.env.development?
  devise_for :users
  root to: "tops#index"
  resources :items
  resources :school_lunches, only: [:index, :new, :create]
  resources :contacts
  resources :stock_items, only: [:index, :new, :create, :update, :edit, :destroy] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :contact_user_name
    validates :contact_user_email
    validates :contact_user_occupation
    validates :contact_manufacturer
    validates :contact_item_name
  end
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '焼き' },
    { id: 3, name: '揚げ' },
    { id: 4, name: '蒸し' },
    { id: 5, name: 'レンジ' },
    { id: 6, name: '自然解凍' },
    { id: 7, name: '湯せん' },
    { id: 8, name: 'オードブル' },
    { id: 9, name: 'お弁当' },
    { id: 11, name: 'お子様' },
    { id: 12, name: '丼' },
    { id: 13, name: '定食' },
    { id: 14, name: '和食' },
    { id: 15, name: '中華' },
    { id: 16, name: '洋食' },
    { id: 17, name: '前菜' },
    { id: 18, name: '八寸' },
    { id: 19, name: 'ベスト' },
    { id: 20, name: '調味料' },
    { id: 21, name: '肉' },
    { id: 22, name: '野菜' }
  ]
 
   include ActiveHash::Associations
   has_many :stock_items
end
 

app/models/item.rb
class Item < ApplicationRecord

  with_options presence: true do
    validates :manufacturer
    validates :item_name
    validates :standard
    validates :storage_condition
    validates :description
    validates :images
    validates :user_id
  end

  belongs_to :user
  has_many_attached :images

end

app/models/item_connect.rb
class ItemConnect < ApplicationRecord

  belongs_to :stock_item
  belongs_to :tag
end

app/models/item_tag.rb
class ItemTag < ApplicationRecord

  belongs_to :stock_item
  belongs_to :tag
  
end

app/models/items_tag.rb
class ItemsTag

  include ActiveModel::Model
  attr_accessor :stock_item_manufacturer, :stock_item_name, :stock_item_standard, :stock_item_strage_condition, :stock_item_description, :image, :tag_word

  with_options presence: true do
    validates :stock_item_manufacturer
    validates :stock_item_name
    validates :stock_item_standard
    validates :stock_item_strage_condition
    validates :stock_item_description
    validates :image
    validates :tag_word
  end

  def save

    stock_item = StockItem.create(stock_item_manufacturer: stock_item_manufacturer, stock_item_name: stock_item_name, stock_item_standard: stock_item_standard, stock_item_strage_condition: stock_item_strage_condition, stock_item_description: stock_item_description, image: image)
    
    tag = Tag.where(tag_word: tag_word).first_or_initialize
    tag.save

    ItemConnect.create(stock_item_id: stock_item.id, tag_id: tag.id)

  end
    
end

app/models/page_select.rb
class PageSelect < ActiveHash::Base
  self.data = [
    { id: 1, name: '--'},
    { id: 2, name: '新商品情報'},
    { id: 3, name: '学校給食資料'}
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/school_lunch.rb
class SchoolLunch < ApplicationRecord

  belongs_to :user
  has_one_attached :image
end

app/models/stock_item.rb
class StockItem < ApplicationRecord

  has_one_attached :image
  has_many :item_connects, dependent: :destroy
  has_many :tags, through: :item_connects

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  with_options presence: true do
    validates :stock_item_manufacturer
    validates :stock_item_name
    validates :stock_item_standard
    validates :stock_item_strage_condition
    validates :stock_item_description
    validates :image
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :item_connects
  has_many :stock_items, through: :item_connects
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :items
  has_many :school_items
  has_many :contacts
       
  
  with_options presence: true do
    validates :name
    validates :name_ruby, format: {with: /\A[ぁ-んー－]+\z/}
    validates :occupation 
    validates :position
    validates :email
    validates :page_select_id, numericality: { other_than: 1 }
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :page_select

end

app/models/user_contact.rb
class UserContact < ApplicationRecord
  belongs_to :user
  belongs_to :contact
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy, ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver
        redirect_to contacts_path,notice: 'Contact was successfully created.'
      end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:contact_user_name, :contact_user_email, :contact_user_occupation, :contact_manufacturer, :contact_item_name, :message).merge(user_id: current_user.id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to action: :index
    else
      render :show
    end
  end


  private

  def item_params
    params.require(:item).permit(:manufacturer, :item_name, :standard, :storage_condition, :sell_by, :description, images: []).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/school_lunches_controller.rb
class SchoolLunchesController < ApplicationController
  before_action :authenticate_user!

  def index
    @school_lunches = SchoolLunch.all
  end

  def new
    @school_lunch = SchoolLunch.new
  end

  def create
    @school_lunch = SchoolLunch.new(school_lunch_params)
    if @school_lunch.save
      redirect_to root_path
    else
      render :new
    end
  end
  private

  def school_lunch_params
    params.require(:school_lunch).permit(:manufacturer, :lunch_item_name, :image).merge(user_id: current_user.id)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/school_lunches_helper.rb
module SchoolLunchesHelper
end

app/helpers/stock_items_helper.rb
module StockItemsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/school_lunches/_form.html.erb
<%= form_with model: @school_lunch, local: true do |f|%>
  <div class="field">
    <%= f.label :manufacturer, "メーカー名", class: :form_name %><br />
    <%= f.text_field :manufacturer, class: :form_text, id:"item_manufacturer" %>
  </div>

  <div class="field">
    <%= f.label :lunch_item_name, "商品名", class: :form_name %><br />
    <%= f.text_area :lunch_item_name, class: :form_text, id:"new_item_name" %>
  </div>
  <div class="field">
    <%= f.label :image, "新商品の画像", class: :form_name %><br />
    <%= f.file_field :image, id:"item_image", class: :form_name %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :send, class: :form_name  %>
  </div>
<% end %>

app/views/school_lunches/index.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>アルバムサンプル for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>
  <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text">これは写真の解説文付きのカードです。自然に説明を加えることができます。しかしこの文章は少し長いかもしれません。</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">見る</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">編集</button>
                </div>
                <small class="text-muted">9分</small>
              </div>
            </div>
          </div>
        </div>

  <%# 入札商品一覧 %>
  <div class='item-contents'>
    <ul class='item-lists'>

      <% @school_lunches.each do |school_lunch| %>
      <li class='list'>
        <%= link_to school_lunches_path(school_lunch.id), method: :get do %>
          <div class='item-img-content'>
          <%= link_to (image_tag school_lunch.image, class: "item-img"), school_lunches_path(school_lunch.id) %>
        <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item_name'>
            <p><%= link_to school_lunch.manufacturer, school_lunches_path(school_lunch.id), method: :get %></p>
            <p><%= link_to school_lunch.lunch_item_name, school_lunches_path(school_lunch.id), method: :get %></p>
          </h3>
        </div>
      <% end %>
      </li>
    </div>
  </div>
  <%# /入札商品一覧 %>
        
</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">トップに戻る</a>
    </p>
  </div>
</footer>
    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/school_lunches/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">《 入札商品の投稿 》</h2>
        <%= render partial: 'form' %>
    </div>
  </div>
</div>
<%= render "shared/second-footer" %>