config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener_web" if Rails.env.development?
  devise_for :users
  root to: "tops#index"
  resources :items
  resources :school_lunches, only: [:index, :new, :create]
  resources :contacts
  resources :stock_items, only: [:index, :new, :create, :update, :edit, :destroy] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :contact_user_name
    validates :contact_user_email
    validates :contact_user_occupation
    validates :contact_manufacturer
    validates :contact_item_name
  end
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '焼き' },
    { id: 3, name: '揚げ' },
    { id: 4, name: '蒸し' },
    { id: 5, name: 'レンジ' },
    { id: 6, name: '自然解凍' },
    { id: 7, name: '湯せん' },
    { id: 8, name: 'オードブル' },
    { id: 9, name: 'お弁当' },
    { id: 11, name: 'お子様' },
    { id: 12, name: '丼' },
    { id: 13, name: '定食' },
    { id: 14, name: '和食' },
    { id: 15, name: '中華' },
    { id: 16, name: '洋食' },
    { id: 17, name: '前菜' },
    { id: 18, name: '八寸' },
    { id: 19, name: 'ベスト' },
    { id: 20, name: '調味料' },
    { id: 21, name: '肉' },
    { id: 22, name: '野菜' }
  ]
 
   include ActiveHash::Associations
   has_many :stock_items
end
 

app/models/item.rb
class Item < ApplicationRecord

  with_options presence: true do
    validates :manufacturer
    validates :item_name
    validates :standard
    validates :storage_condition
    validates :description
    validates :images
    validates :user_id
  end

  belongs_to :user
  has_many_attached :images

end

app/models/item_connect.rb
class ItemConnect < ApplicationRecord

  belongs_to :stock_item
  belongs_to :tag
end

app/models/item_tag.rb
class ItemTag < ApplicationRecord

  belongs_to :stock_item
  belongs_to :tag
  
end

app/models/items_tag.rb
class ItemsTag

  include ActiveModel::Model
  attr_accessor :stock_item_manufacturer, :stock_item_name, :stock_item_standard, :stock_item_strage_condition, :stock_item_description, :image, :tag_word

  with_options presence: true do
    validates :stock_item_manufacturer
    validates :stock_item_name
    validates :stock_item_standard
    validates :stock_item_strage_condition
    validates :stock_item_description
    validates :image
    validates :tag_word
  end

  def save

    stock_item = StockItem.create(stock_item_manufacturer: stock_item_manufacturer, stock_item_name: stock_item_name, stock_item_standard: stock_item_standard, stock_item_strage_condition: stock_item_strage_condition, stock_item_description: stock_item_description, image: image)
    
    tag = Tag.where(tag_word: tag_word).first_or_initialize
    tag.save

    ItemConnect.create(stock_item_id: stock_item.id, tag_id: tag.id)

  end
    
end

app/models/page_select.rb
class PageSelect < ActiveHash::Base
  self.data = [
    { id: 1, name: '--'},
    { id: 2, name: '新商品情報'},
    { id: 3, name: '学校給食資料'}
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/school_lunch.rb
class SchoolLunch < ApplicationRecord

  belongs_to :user
  has_one_attached :image
end

app/models/stock_item.rb
class StockItem < ApplicationRecord

  has_one_attached :image
  has_many :item_connects, dependent: :destroy
  has_many :tags, through: :item_connects

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  with_options presence: true do
    validates :stock_item_manufacturer
    validates :stock_item_name
    validates :stock_item_standard
    validates :stock_item_strage_condition
    validates :stock_item_description
    validates :image
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :item_connects
  has_many :stock_items, through: :item_connects
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :items
  has_many :school_items
  has_many :contacts
       
  
  with_options presence: true do
    validates :name
    validates :name_ruby, format: {with: /\A[ぁ-んー－]+\z/}
    validates :occupation 
    validates :position
    validates :email
    validates :page_select_id, numericality: { other_than: 1 }
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :page_select

end

app/models/user_contact.rb
class UserContact < ApplicationRecord
  belongs_to :user
  belongs_to :contact
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy, ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver
        redirect_to contacts_path,notice: 'Contact was successfully created.'
      end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:contact_user_name, :contact_user_email, :contact_user_occupation, :contact_manufacturer, :contact_item_name, :message).merge(user_id: current_user.id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to action: :index
    else
      render :show
    end
  end


  private

  def item_params
    params.require(:item).permit(:manufacturer, :item_name, :standard, :storage_condition, :sell_by, :description, images: []).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/school_lunches_helper.rb
module SchoolLunchesHelper
end

app/helpers/stock_items_helper.rb
module StockItemsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/index.html.erb
<!DOCTYPE HTML>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>カルーセルテンプレート for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/carousel/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
  </head>
  <body>
    
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>N-Web-Apprication</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
        </ul>
        <div class="d-flex">
        <% if user_signed_in? && current_user.admin? %>
        <%= link_to '新商品掲載', new_item_path, method: :get, class: "top_button" %>
        <%= link_to '在庫商品掲載', new_stock_item_path, method: :get, class: "top_button" %>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "top_button" %>
          <%= link_to current_user.name, class: "u-name" %>
        <% else %>
          <a href= "/users/sign_up" class="top_button">新規登録</a>
          <a href= "/users/sign_in" class="top_button">ログイン</a>
        <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

<main>

    <div class="carousel-inner">
        <img src="/assets/icon_top2.jpeg" width="100%" height="70%" class="imgResponsive">
    </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="image-position">
      <div class="col-lg-4">
        <img src="/assets/icon_new_item.jpeg" class="bd-placeholder-img rounded-circle" width="200" height="200">
        <div class="list-1-1">
          <div class="list1-2">
            <h2>新商品情報</h2>
          </div>
          <p>・各社の新商品情報を集約！</p>
          <p>・検索の手間を大幅削減！</p>
            <div class="list1-1-1">
              <p><a href= "items#index" button type="button" class="btn btn-outline-primary">新商品を見る &raquo;</a></p>
            </div>
        </div>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img src="/assets/icon_zaiko.jpeg" class="bd-placeholder-img rounded-circle" width="200" height="200">
        <h2>在庫商品検索</h2>
        <p>・在庫品を見て選びたい！</p>
        <p>・少しだけ欲しい！</p>
          <div class="list2-2">
            <p><a href="stock_items#index" class="btn btn-outline-primary" role="button">在庫商品を見る &raquo;</a></p>
          </div>
      </div><!-- /.col-lg-4 -->
      <div class="list-3">
        <img src="/assets/icon_lunch.jpeg" class="bd-placeholder-img rounded-circle" width="180" height="200">
        <h2>給食関連資料</h2>
        <p>・いつでも成分が見れる！</p>
        <p>・エリア内全てが閲覧可能！</p>
          <div class="list3-3">
            <p><a class="btn btn-outline-primary" href="school_lunches#index" role="button">企画書を見る &raquo;</a></p>
          </div>
      </div>
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">ナカヤマフーズオンライン<span class="text-muted"></span></h2>
        <p class="lead">創業70周年・業務用食品】食のプロ愛用業務用食品ネット通販・ナカヤマフーズオンライン 食のプロ御用達のこだわりの高品質・大容量サイズの業務用食品・業務用食材を、豊富な種類からお選びいただけます。一般の方も購入大歓迎！ぜひともご利用ください。</p>
        <p><%= link_to "ナカヤマフーズへ", "https://nakayama-foods.com", class: "btn btn-outline-info" %></p>
        <p><img src="/assets/icon_foods2.jpeg"width="500" height="200"></p>
      </div>
      <div class="col-md-5">
        <img src="assets/icon_foods.png"width="400" height="400">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">ハッピーナチュラル<span class="text-muted"></span></h2>
        <p class="lead">オーガニック＆自然派商品ネット通販</p>
        <p><%=link_to "ハッピーナチュラルへ", "https://www.happynatural.jp", class: "btn btn-outline-danger" %></p>
        <img src="assets/icon_happy.svg"width="400" height="200">
      </div>
      <div class="col-md-5 order-md-1">
        <img src="assets/icon_happy2.png"width="300" height="300">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">（株）ナカヤマ<span class="text-muted"></span></h2>
        <p class="lead">・化成部（１課 2課 3課）<br>・ラベル部（デザイン室）<br>・食品部<br>・ハッピーナチュラル</p>
        <p><%= link_to "（株）ナカヤマへ", "https://www.net-nakayama.co.jp", class: "btn btn-outline-info" %></p>
        
      </div>
      <div class="col-md-5">
        
        <img src="assets/icon_nakayama.png"width="400" height="200">
      </div>
    </div>

    <hr class="featurette-divider">

    

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">トップに戻る</a></p>
    <p>&copy; 2017-2021 Company, Inc. &middot; <a href="#">プライバシー</a> &middot; <a href="#">利用規約</a></p>
  </footer>
</main>


    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

      
  </body>
</html>