config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener_web" if Rails.env.development?
  devise_for :users
  root to: "tops#index"
  resources :items
  resources :school_lunches, only: [:index, :new, :create]
  resources :contacts
  resources :stock_items, only: [:index, :new, :create, :update, :edit, :destroy] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :contact_user_name
    validates :contact_user_email
    validates :contact_user_occupation
    validates :contact_manufacturer
    validates :contact_item_name
  end
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '焼き' },
    { id: 3, name: '揚げ' },
    { id: 4, name: '蒸し' },
    { id: 5, name: 'レンジ' },
    { id: 6, name: '自然解凍' },
    { id: 7, name: '湯せん' },
    { id: 8, name: 'オードブル' },
    { id: 9, name: 'お弁当' },
    { id: 11, name: 'お子様' },
    { id: 12, name: '丼' },
    { id: 13, name: '定食' },
    { id: 14, name: '和食' },
    { id: 15, name: '中華' },
    { id: 16, name: '洋食' },
    { id: 17, name: '前菜' },
    { id: 18, name: '八寸' },
    { id: 19, name: 'ベスト' },
    { id: 20, name: '調味料' },
    { id: 21, name: '肉' },
    { id: 22, name: '野菜' }
  ]
 
   include ActiveHash::Associations
   has_many :stock_items
end
 

app/models/item.rb
class Item < ApplicationRecord

  with_options presence: true do
    validates :manufacturer
    validates :item_name
    validates :standard
    validates :storage_condition
    validates :description
    validates :images
    validates :user_id
  end

  belongs_to :user
  has_many_attached :images

end

app/models/item_connect.rb
class ItemConnect < ApplicationRecord

  belongs_to :stock_item
  belongs_to :tag
end

app/models/item_tag.rb
class ItemTag < ApplicationRecord

  belongs_to :stock_item
  belongs_to :tag
  
end

app/models/items_tag.rb
class ItemsTag

  include ActiveModel::Model
  attr_accessor :stock_item_manufacturer, :stock_item_name, :stock_item_standard, :stock_item_strage_condition, :stock_item_description, :image, :tag_word

  with_options presence: true do
    validates :stock_item_manufacturer
    validates :stock_item_name
    validates :stock_item_standard
    validates :stock_item_strage_condition
    validates :stock_item_description
    validates :image
    validates :tag_word
  end

  def save

    stock_item = StockItem.create(stock_item_manufacturer: stock_item_manufacturer, stock_item_name: stock_item_name, stock_item_standard: stock_item_standard, stock_item_strage_condition: stock_item_strage_condition, stock_item_description: stock_item_description, image: image)
    
    tag = Tag.where(tag_word: tag_word).first_or_initialize
    tag.save

    ItemConnect.create(stock_item_id: stock_item.id, tag_id: tag.id)

  end
    
end

app/models/page_select.rb
class PageSelect < ActiveHash::Base
  self.data = [
    { id: 1, name: '--'},
    { id: 2, name: '新商品情報'},
    { id: 3, name: '学校給食資料'}
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/school_lunch.rb
class SchoolLunch < ApplicationRecord

  belongs_to :user
  has_one_attached :image
end

app/models/stock_item.rb
class StockItem < ApplicationRecord

  has_one_attached :image
  has_many :item_connects, dependent: :destroy
  has_many :tags, through: :item_connects

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  with_options presence: true do
    validates :stock_item_manufacturer
    validates :stock_item_name
    validates :stock_item_standard
    validates :stock_item_strage_condition
    validates :stock_item_description
    validates :image
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :item_connects
  has_many :stock_items, through: :item_connects
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :items
  has_many :school_items
  has_many :contacts
       
  
  with_options presence: true do
    validates :name
    validates :name_ruby, format: {with: /\A[ぁ-んー－]+\z/}
    validates :occupation 
    validates :position
    validates :email
    validates :page_select_id, numericality: { other_than: 1 }
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :page_select

end

app/models/user_contact.rb
class UserContact < ApplicationRecord
  belongs_to :user
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_ruby, :occupation, :position, :page_select_id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy, ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver
        redirect_to contacts_path,notice: 'Contact was successfully created.'
      end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:contact_user_name, :contact_user_email, :contact_user_occupation, :contact_manufacturer, :contact_item_name, :message).merge(user_id: current_user.id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to action: :index
    else
      render :show
    end
  end


  private

  def item_params
    params.require(:item).permit(:manufacturer, :item_name, :standard, :storage_condition, :sell_by, :description, images: []).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/school_lunches_helper.rb
module SchoolLunchesHelper
end

app/helpers/stock_items_helper.rb
module StockItemsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :'お名前' %>
    <%= form.text_field :current_user.name %>
  </div>

  <div class="field">
    <%= form.label :'メールアドレス' %>
    <%= form.text_field :current_user.email %>
  </div>

  <div class="field">
    <%= form.label :'店名' %>
    <%= form.text_field :current_user.occupation %>
  </div>

  <div class="field">
    <%= form.label :'メーカー名' %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :'商品名' %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :'メッセージ' %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
<%= render "shared/second-header" %>

<body>

  <div class='contact'>
    <div class='contact-top'>
      <h1>メール送信完了！</h1>
    </div>
    <div class='contact-main'>
      <h1>サンプル依頼ありがとうございます。</h1>
    </div>
    <ul class='contact-under'>
        <li>ただいま、管理人へサンプル依頼を送信しました。</li>
        <li>メーカーから取り寄せ、担当営業が持参いたします。</li>
        <li>納品までに、おおむね１週間頂いておりますので、ご了承下さい。</li>
        <li>又、無償でサンプルが提供できない場合もございますので、合わせてご了承下さい。</li>
    </ul>
    <h2>
      <%= link_to "一覧へ戻る", items_path, method: :get, class: 'contact-return' %>
    </h2>
  </div>
</body>

app/views/contacts/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  </head>

<%= render "shared/second-header" %>

<%= form_with model: @contact, class: 'registration-main', local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        サンプル依頼
      </h1>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">お名前</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :contact_user_name, class:"input-default", id:"user_name", placeholder: "(例)山田勉" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">メールアドレス</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.email_field :contact_user_email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
    </div>
    
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">所属</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :contact_user_occupation, class:"input-default", id: "user_occupation", placeholder:"店名・会社名等" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">メーカー名</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :contact_manufacturer, class:"input-default", id:"contact_mamufacture", placeholder:"味の素・ニチレイ等" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">商品名</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :contact_item_name, class:"input-default", id:"contact_item_name", placeholder:"〇〇コロッケ等" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">特記事項</label>
      </div>
      <%= f.text_area :message, class:"input-default", id:"contact_message", placeholder:"補足があればご記入ください" %>
    </div>

    <div class="form-group">
      <h2 class='form-bottom-text'>
      
      </h2>
    </div>
    <div class='register-btn'>
      <%= f.submit "サンプル依頼" ,class:"register-red-btn" %>
    </div>
  </div>
<% end %>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>

    <%= render "shared/footer" %>
</main>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/items/_form.html.erb
<%= form_with model: @item, local: true do |f| %>

<%= render 'shared/error_messages', model: f.object %>

  <div class="field">
    <%= f.label :manufacturer, "メーカー名", class: :form_name %><br />
    <%= f.text_field :manufacturer, class: :form_text, id:"item_manufacturer" %>
  </div>

  <div class="field">
    <%= f.label :item_name, "商品名", class: :form_name %><br />
    <%= f.text_area :item_name, class: :form_text, id:"new_item_name" %>
  </div>

  <div class="field">
    <%= f.label :standard, "規格", class: :form_name %><br />
    <%= f.text_area :standard, class: :form_text, id:"item_standard" %>
  </div>

  <div class="field">
    <%= f.label :storage_condition, "保存方法", class: :form_name %><br />
    <%= f.text_area :storage_condition, class: :form_text, id:"item_storage_condition" %>
  </div>

  <div class="field">
    <%= f.label :description, "商品説明", class: :form_name %><br />
    <%= f.text_area :description, class: :form__text, id:"item_description" %>
  </div>

  <div class="parallel">
    <div class="field">
      <%= f.label :images, "新商品の画像", class: :form_name %><br />
      <%= f.file_field :images, name: 'item[images][]', id:"item_image", class: :form_name %>
    </div>

    <div class="actions">
      <%= f.submit "保存する", class: :send, class: :form_name  %>
    </div>
    <div id="image-list" ></div>
  </div>
<% end %>

<% @item.images.each do |image| %>
  <%= image_tag image, class: 'images' %>
<% end %>

app/views/items/edit.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>アルバムサンプル for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>

<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong>N_Web_Apprication</strong>
    </a>
    <div class="d-flex">
      <%= link_to "トップへ", root_path, class: "top_button" %>
    </div>
  </div>
</div>

<div class='registration-main'>
  <div class='form-wrap'>
    <div class="form__wrapper">
      <h2 class="page-heading"> 新商品の編集 </h2>
        <%= render partial: 'form' %>
    </div>
  </div>
</div>
<%= render "shared/second-footer" %>

<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</html>

app/views/items/new.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>アルバムサンプル for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>

<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong>N_Web_Apprication</strong>
    </a>
    <div class="d-flex">
      <%= link_to "トップへ", root_path, class: "top_button" %>
    </div>
  </div>
</div>


<div class='registration-main'>
  <div class='form-wrap'>
    <div class="form__wrapper">
      <h2 class="page-heading"> 新商品の投稿 </h2>
        
        <%= render partial: 'form' %>
        
    </div>
  </div>
</div>

<%= render "shared/second-footer" %>

<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</html>

app/views/items/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- "画像の拡大" -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript">
    </script>

  </head>
<body>
<%= render "shared/third-header" %>

<main class="item-main">
  <div class="item-inner">
    <div class="item__wrapper">
      <p class="item__hedding">
        <%= @item.item_name %>
      </p>
      <div class="show-top-image">
        <% @item.images.each do |image| %>
          <%= link_to image, "data-lightbox": image do %>
            <%= image_tag image, class:'show-image' %>
          <% end %>
        <% end %>
      </div>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">メーカー名</th>
            <th scope="col">商品名  </th>
            <th scope="col">商品規格  </th>
            <th scope="col">温度帯  </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row"><%= @item.manufacturer %></th>
            <td><%= @item.item_name %></td>
            <td><%= @item.standard %></td>
            <td><%= @item.storage_condition %></td>
          </tr>
        </tbody>
      </table>
      <div class="item-description">
        <div class="item-discription-name">
          <%= '《商品説明》' %>
          <div style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333;">
            <%= @item.description %>
          </div>
        </div>
      </div>
        <div class="item-edit">
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to "編集する", edit_item_path(@item.id),method: :get,  class: "btn btn-outline-secondary" %>
            <%= link_to "削除する", item_path(@item.id),method: :delete, class: "btn btn-outline-secondary" %>
          <% end %>
        </div>
        <%= link_to new_contact_path, method: :get, class: 'purchase-btn' do %>
          <span class='purchase-btn-text'>サンプル  依頼する</span>
          <%= image_tag '177535.jpg' , size: '185x50' ,class: "purchase-btn-icon" %>
        <% end %>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>

    <%= render "shared/footer" %>
</body>
</main>