config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener_web" if Rails.env.development?
  devise_for :users
  root to: "tops#index"
  resources :items
  resources :school_lunches, only: [:index, :new, :create]
  resources :contacts
  resources :stock_items, only: [:index, :new, :create, :update, :edit, :destroy] do
    collection do
      get 'search'
    end
  end
end

app/models/stock_item.rb
class StockItem < ApplicationRecord

  has_one_attached :image
  has_many :item_connects, dependent: :destroy
  has_many :tags, through: :item_connects

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  with_options presence: true do
    validates :stock_item_manufacturer
    validates :stock_item_name
    validates :stock_item_standard
    validates :stock_item_strage_condition
    validates :stock_item_description
    validates :image
  end
end

app/controllers/stock_items_controller.rb
class StockItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stock_item, only: [:edit, :destroy]
  before_action :search_stock_item, only: [:index, :search]

  def index
    @stock_items = StockItem.all.order(created_at: :desc)
  end

  def new
    @stock_item = ItemsTag.new
  end

  def create
    @stock_item = ItemsTag.new(stock_item_params)
    if @stock_item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @stock_item.update(stock_item_params)
      redirect_to contacts_path
    else
      render :edit
    end
  end

  def destroy
    if @stock_item.destroy
      redirect_to root_path
    else
      render :index
    end
  end

  def search
    @results = @q.result.includes(:tags)
  end

  private

  def stock_item_params
    params.require(:items_tag).permit(:stock_item_manufacturer, :stock_item_name, :stock_item_standard, :stock_item_strage_condition, :stock_item_description, :image, :tag_word)
  end

  def search_stock_item
    @q = StockItem.ransack(params[:q])
  end

  def set_stock_item
    @stock_item = StockItem.find(params[:id])
  end

end

app/helpers/stock_items_helper.rb
module StockItemsHelper
end

app/views/stock_items/edit.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>アルバムサンプル for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
    <link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>

<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong>N_Web_Apprication</strong>
    </a>
    <div class="d-flex">
      <%= link_to "トップへ", root_path, class: "top_button" %>
    </div>
  </div>
</div>

<%#<%= render 'shared/error_messages', model: f.object %>

<div class='registration-main'>
  <div class='form-wrap'>
    <div class="form__wrapper">
      <h2 class="page-heading"> 在庫商品の投稿 </h2>
        
      <%= form_with model: @stock_item, url: stock_item_path, method: :put, local: true do |f|%>
      <div class="field">
        <%= f.label :stock_item_manufacturer, "メーカー名", class: :form_name %><br />
        <%= f.text_field :stock_item_manufacturer, class: :form_text, id:"item_manufacturer" %>
      </div>

      <div class="field">
        <%= f.label :stock_item_name, "商品名", class: :form_name %><br />
        <%= f.text_field :stock_item_name, class: :form_text, id:"new_item_name" %>
      </div>

      <div class="field">
        <%= f.label :stock_item_standard, "規格", class: :form_name %><br />
        <%= f.text_field :stock_item_standard, class: :form_text, id:"item_standard" %>
      </div>

      <div class="field">
        <%= f.label :stock_item_strage_condition, "保存方法", class: :form_name %><br />
        <%= f.text_field :stock_item_strage_condition, class: :form_text, id:"item_strage_condition" %>
      </div>

      <div class="field">
        <%= f.label :stock_item_description, "商品説明", class: :form_name %><br />
        <%= f.text_area :stock_item_description, class: :form__text, id:"item_description" %>
      </div>

      <div class="field">
        <%= f.label :name, "タグ", class: :form_name %><br />
        <%= f.text_field :name, class: :form__text, id:"item_description" %>
      </div>

      <div class="parallel">
        <div class="field">
          <%= f.label :image, "新商品の画像", class: :form_name %><br />
          <%= f.file_field :image, id:"item_image", class: :form_name %>
        </div>

        <div class="actions">
          <%= f.submit "保存する", class: :send, class: :form_name  %>
        </div>
        <div id="image-list" ></div>
      </div>
    </div>
  </div>
<% end %>



</div>
<%= render "shared/second-footer" %>

<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</html>

app/views/stock_items/index.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>アルバムサンプル for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- "画像の拡大" -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript">
    </script>

  </head>
  <body>
    
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">撮影者や撮影した背景など、アルバムに関する情報を追加しましょう。いくつかの文を書いておくと、友達が写真を選ぶ手助けになるかもしれません。また、写真は SNS や連絡先へとリンクしておきましょう。</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Twitter でフォローする</a></li>
            <li><a href="#" class="text-white">Facebook でいいねする</a></li>
            <li><a href="#" class="text-white">Email を送る</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>N-Web-Apprication</strong>
      </a>
      <div class="d-flex">
        <%= link_to "トップへ", root_path, class: "top_button" %>
      </div>
    </div>
  </div>

<main>

  <%# 商品の検索 %>
  <div class='stock_item_search'>
    <h1>
      在庫商品検索
    </h1>
    <%= search_form_for @q, url: search_stock_items_path do |f| %>
      <%= f.label :tag_word_eq, 'タグ' %>
      <%= f.collection_select :tags_tag_word_eq, Genre.all, :name, :name, include_blanck: '指定なし', id: "tag-select" %>
      <%= f.submit '検索'%>
    <% end %>
  </div>

  <%# 在庫商品一覧 %>
  <div class='item-contents'>
    <ul class='item-lists'>
      <% @stock_items.each do |stock_item| %>
        <div class='list'>
          <div class='item-img-content'>
            <ul class="item-index">
              <li><%= stock_item.stock_item_manufacturer %></li>
              <li><%= stock_item.stock_item_name %></li>
            </ul>
              <%= link_to stock_item.image, "data-lightbox": stock_item.image do %>
                <%= image_tag stock_item.image, class: "item-img"%>
              <% end %>
          </div>
          <div class='tag'>
            <li class='tag-lists'>
              <% stock_item.tags.each do |tag| %>
                <p><%= tag.tag_word %></p>
              <% end %>
            </li>
          </div>
          <div class="stock_item-edit">
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to "編集する", edit_stock_item_path(stock_item.id),method: :get,  class: "btn btn-outline-secondary" %>
            <%= link_to "削除する", stock_item_path(stock_item.id),method: :delete, class: "btn btn-outline-secondary" %>
          <% end %>
        </div>
        </div>
      <% end %>
    </ul>
  </div>
  <%# /在庫商品一覧 %>
  </body>

</main>

<footer class="container">
    <p class="float-end"><a href="/">トップに戻る</a></p>
    <p>&copy; 2017-2021 Company, Inc. &middot; <a href="#">プライバシー</a> &middot; <a href="#">利用規約</a></p>
</footer>


    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

      
</html>

app/views/stock_items/new.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>アルバムサンプル for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
    <link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>

<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong>N_Web_Apprication</strong>
    </a>
    <div class="d-flex">
      <%= link_to "トップへ", root_path, class: "top_button" %>
    </div>
  </div>
</div>

<%#<%= render 'shared/error_messages', model: f.object %>

<div class='registration-main'>
  <div class='form-wrap'>
    <div class="form__wrapper">
      <h2 class="page-heading"> 在庫商品の投稿 </h2>
        
      <%= form_with model: @stock_item, url: stock_items_path, local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>
      
        <div class="field">
          <%= f.label :stock_item_manufacturer, "メーカー名", class: :form_name %><br />
          <%= f.text_field :stock_item_manufacturer, class: :form_text, id:"item_manufacturer" %>
        </div>

        <div class="field">
          <%= f.label :stock_item_name, "商品名", class: :form_name %><br />
          <%= f.text_field :stock_item_name, class: :form_text, id:"new_item_name" %>
        </div>

        <div class="field">
          <%= f.label :stock_item_standard, "規格", class: :form_name %><br />
          <%= f.text_field :stock_item_standard, class: :form_text, id:"item_standard" %>
        </div>

        <div class="field">
          <%= f.label :stock_item_strage_condition, "保存方法", class: :form_name %><br />
          <%= f.text_field :stock_item_strage_condition, class: :form_text, id:"item_strage_condition" %>
        </div>

        <div class="field">
          <%= f.label :stock_item_description, "商品説明", class: :form_name %><br />
          <%= f.text_area :stock_item_description, class: :form__text, id:"item_description" %>
        </div>

        <div class="field">
          <%= f.label :tag_word, "タグ", class: :form_name %><br />
          <%= f.collection_select(:tag_word, Genre.all, :name, :name, {}, {class:"form__text"}) %>
        </div>

        <div class="parallel">
          <div class="field">
            <%= f.label :image, "新商品の画像", class: :form_name %><br />
            <%= f.file_field :image, id:"item_image", class: :form_name %>
          </div>
        </div>

        <div class="actions">
          <%= f.submit "保存する", class: :send, class: :form_name  %>
        </div>
        <div id="tag-list" ></div>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/second-footer" %>

<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</html>

app/views/stock_items/search.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>アルバムサンプル for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- "画像の拡大" -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript">
    </script>

  </head>
  <body>
    
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">撮影者や撮影した背景など、アルバムに関する情報を追加しましょう。いくつかの文を書いておくと、友達が写真を選ぶ手助けになるかもしれません。また、写真は SNS や連絡先へとリンクしておきましょう。</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Twitter でフォローする</a></li>
            <li><a href="#" class="text-white">Facebook でいいねする</a></li>
            <li><a href="#" class="text-white">Email を送る</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong>N_Web_Apprication</strong>
    </a>
    <div class="d-flex">
      <%= link_to "トップへ", root_path, class: "top_button" %>
      <%= link_to "一覧へ", stock_items_path, class: "top_button" %>
    </div>
  </div>
</div>

<main>

<div class='stock_item_search'>
  <h1>
    検索結果
  </h1>
</div>
<div class='item-contents'>
  <ul class='item-lists'>
    <% if @results.length !=0 %>
      <% @results.each do |result| %>
        <div class='list'>
          <div class='item-img-content'>
            <ul class="item-index">
              <li><%= result.stock_item_manufacturer %></li>
              <li><%= result.stock_item_name %></li>
            </ul>
            <div class='item-img-content'>
              <%= link_to result.image, "data-lightbox": result.image do %>
                <%= image_tag result.image, class: "item-img"%>
              <% end %>
            </div>
          </div>
          <div class='tag'>
            <li class='tag-lists'>
              <% result.tags.each do |tag| %>
                <p><%= tag.tag_word %></p>
              <% end %>
            </li>
          </div>
        </div>
      <% end %>
    <% else %>
      該当する商品はありません
    <% end %>
  </ul>
</div>

  <br>
  <%= link_to '一覧ページへ戻る', stock_items_path %>
  </body>

</main>

<footer class="container">
    <p class="float-end"><a href="/">トップに戻る</a></p>
    <p>&copy; 2017-2021 Company, Inc. &middot; <a href="#">プライバシー</a> &middot; <a href="#">利用規約</a></p>
</footer>


    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

      
</html>